/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_kerberos_KerberosOperationNativeWrapper */

#ifndef _Included_edu_mit_kerberos_KerberosOperationNativeWrapper
#define _Included_edu_mit_kerberos_KerberosOperationNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KerberosOperationNativeWrapper
 * Method:    nativeSetEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KerberosOperationNativeWrapper_nativeSetEnv
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_mit_kerberos_KinitOperationNativeWrapper */

#ifndef _Included_edu_mit_kerberos_KinitOperationNativeWrapper
#define _Included_edu_mit_kerberos_KinitOperationNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KinitOperationNativeWrapper
 * Method:    nativeKinit
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KinitOperationNativeWrapper_nativeKinit
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_mit_kerberos_KlistOperationNativeWrapper */

#ifndef _Included_edu_mit_kerberos_KlistOperationNativeWrapper
#define _Included_edu_mit_kerberos_KlistOperationNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KlistOperationNativeWrapper
 * Method:    nativeKlist
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KlistOperationNativeWrapper_nativeKlist
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_mit_kerberos_KdestroyOperationNativeWrapper */

#ifndef _Included_edu_mit_kerberos_KdestroyOperationNativeWrapper
#define _Included_edu_mit_kerberos_KdestroyOperationNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KdestroyOperationNativeWrapper
 * Method:    nativeKdestroy
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KdestroyOperationNativeWrapper_nativeKdestroy
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_mit_kerberos_KvnoOperationNativeWrapper */

#ifndef _Included_edu_mit_kerberos_KvnoOperationNativeWrapper
#define _Included_edu_mit_kerberos_KvnoOperationNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KvnoOperationNativeWrapper
 * Method:    nativeKvno
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KvnoOperationNativeWrapper_nativeKvno
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
