/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_kerberos_KerberosOperations */

#ifndef _Included_edu_mit_kerberos_KerberosOperations
#define _Included_edu_mit_kerberos_KerberosOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_kerberos_KerberosOperations
 * Method:    nativeSetKRB5CCNAME
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KerberosOperationNativeWrapper_nativeSetEnv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_mit_kerberos_KerberosOperations
 * Method:    nativeKinit
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KinitOperationNativeWrapper_nativeKinit
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_mit_kerberos_KerberosOperations
 * Method:    nativeKlist
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KlistOperationNativeWrapper_nativeKlist
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_mit_kerberos_KerberosOperations
 * Method:    nativeKvno
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KvnoOperationNativeWrapper_nativeKvno
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_mit_kerberos_KerberosOperations
 * Method:    nativeKdestroy
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_kerberos_KdestroyOperationNativeWrapper_nativeKdestroy
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
